### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by py4h0n** [RiskSense-Ops/MS17-010#1]
When i testing my server, it shows exception like this:
[-] [192.168.255.132] Exception: Buffer size too small (0 instead of at least 32 bytes)

Target Server: windows7 Ultimate 7600 x86 32
I‘m sure that i did not patch the MS17-010

**Comment by zerosum0x0** [comment]
Yes, it was unclear but it will only work against 7601 x64.

Stay tuned for more support in the future.
