### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by okiwoki** [RiskSense-Ops/MS17-010#5]
When attempting to build using the command: "python build.py all > output.txt"

I'm getting the following errors:

src/single/createthread.asm:22: error: symbol `block_find_dll' undefined.
src/single/createthread.asm:37: error: symbol `block_api_direct' undefined.

After this error, it also deletes the "createthread.bin" file in payloads/x64/bin

**Comment by zerosum0x0** [comment]
See #2 

Fixed in 8d0514554f34662b695defe25fc0bb38ff96bb3b
